spring.application.name=cinemaApp

#Later delete
spring.datasource.url=jdbc:postgresql://localhost:5432/CinemaApp


spring.datasource.username=postgres
spring.datasource.password=SUBD123
spring.jpa.hibernate.ddl-auto=update

app.secret = "secretKey1488rtfhokrthiotrkhtriohkrtikhtrhrth"

#logging
logging.level.org.hibernate.SQL=DEBUG
spring.jpa.show-sql=true
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE


#static
spring.web.resources.static-locations=classpath:/static/,classpath:/uploads/,file:./uploads/
spring.web.resources.cache.period=3600
spring.servlet.multipart.max-file-size=4000MB
spring.servlet.multipart.max-request-size=4000MB
spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=4KB


#Actuator
spring.security.user.name=admin
spring.security.user.password=supersecurepassword
management.endpoint.loggers.enabled=true
management.endpoints.web.exposure.include= health,info,env
